name: "Vida Google Assistant"
description: "Vida Google Assistant add-on"
version: "0.1.0"
slug: "vida-google-assistant"
init: false
hassio_api: true
homeassistant_api: true
hassio_role: "admin"
map:
  - backup:rw
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
image: "ghcr.io/gordonampotech/vida-google-assistant"
ingress: true
ingress_port: 8100
host_network: true
